[features]
seeds = false
skip-lint = false

[programs.devnet]
history_game = "8qUBTgX99v5EhxbAaxuqS94rgfRhnLrTgW66Gh9BvLKN"

[programs.localnet]
history_game = "8qUBTgX99v5EhxbAaxuqS94rgfRhnLrTgW66Gh9BvLKN"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "python3 ../../scripts/test_solana_program.py && python3 ../../scripts/test_reward_distributor.py"

[test]
startup_wait = 10000
